### ISSUE TITLE
Broken link for Bounties

### ISSUE THREAD

**Issue by 0xMimir** [ethersphere/ethswarm-nextjs#98]
Link for `Bounties` is [https://www.gitcoin.co/fairdatasociety](https://www.gitcoin.co/fairdatasociety) which returns 404 
![image](https://github.com/ethersphere/ethswarm-nextjs/assets/108837858/7c9eeed3-470d-48a8-a2a7-fc232773a50a)

**Comment by martink635** [comment]
This is now fixed.
